#include "_AutoAbility.h"
/*
	Key : Byte Value
	Value : Auto Ability Object { std::string name, std::string name }
*/
std::map<uint16_t, AutoAbilityObject> _AutoAbility = {
	{ 0x8000, { "Sensor", "View enemy data during battle." } },
	{ 0x8001, { "First Strike", "Act first at beginning of battle." } },
	{ 0x8002, { "Initiative", "Raises party's chances for a preemptive strike." } },
	{ 0x8003, { "Counterattack", "Strike back after being physically attacked." } },
	{ 0x8004, { "Evade & Counter", "Evade physical attack and strike back." } },
	{ 0x8005, { "Magic Counter", "Strike back after being attacked with magic." } },
	{ 0x8006, { "Magic Booster", "Use more MP to heighten spell power." } },
	{ 0x8007, { "Alchemy", "Doubles the potency of recovery items." } },
	{ 0x8008, { "Auto-Potion", "Automatically use items to recover HP when damaged." } },
	{ 0x8009, { "Auto-Med", "Automatically use items to cure status ailments." } },
	{ 0x800A, { "Auto-Phoenix", "Automatically use Phoenix Down on KO'd character." } },
	{ 0x800B, { "Piercing", "Deal normal damage to armored enemies." } },
	{ 0x800C, { "Half MP Cost", "Reduces MP cost of spells by half." } },
	{ 0x800D, { "One MP Cost", "Reduces MP cost of spells to 1." } },
	{ 0x800E, { "Double Overdrive", "Charges Overdrive at double speed." } },
	{ 0x800F, { "Triple Overdrive", "Charges Overdrive at triple speed." } },
	{ 0x8010, { "SOS Overdrive", "Charges Overdrive at double speed when HP is low." } },
	{ 0x8011, { "Overdrive ? AP", "Earn more AP instead of charging Overdrive gauge." } },
	{ 0x8012, { "Double AP", "Doubles amount of AP earned." } },
	{ 0x8013, { "Triple AP", "Triples amount of AP earned." } },
	{ 0x8014, { "No AP", "No AP earned after battles." } },
	{ 0x8015, { "Pickpocket", "Improves odds of stealing rare items." } },
	{ 0x8016, { "Master Thief", "Steal only rare items." } },
	{ 0x8017, { "Break HP Limit", "Allows max HP to exceed 9999." } },
	{ 0x8018, { "Break MP Limit", "Allows max MP to exceed 999." } },
	{ 0x8019, { "Break Damage Limit", "Allows max damage to exceed 9999." } },
	{ 0x801A, { "Gillionaire", "Doubles amount of gil earned." } },
	{ 0x801B, { "HP Stroll", "Automatically recover HP while walking." } },
	{ 0x801C, { "MP Stroll", "Automatically recover MP while walking." } },
	{ 0x801D, { "No Encounters", "No random enemy encounters." } },
	{ 0x801E, { "Firestrike", "Adds fire element to attacks and skills." } },
	{ 0x801F, { "Fire Ward", "Reduces fire damage by half." } },
	{ 0x8020, { "Fireproof", "Grants immunity to fire attacks." } },
	{ 0x8021, { "Fire Eater", "Converts fire damage to HP." } },
	{ 0x8022, { "Icestrike", "Adds ice element to attacks and skills." } },
	{ 0x8023, { "Ice Ward", "Reduces ice damage by half." } },
	{ 0x8024, { "Iceproof", "Grants immunity to ice attacks." } },
	{ 0x8025, { "Ice Eater", "Converts ice damage to HP." } },
	{ 0x8026, { "Lightningstrike", "Adds lightning element to attacks and skills." } },
	{ 0x8027, { "Lightning Ward", "Reduces lightning damage by half." } },
	{ 0x8028, { "Lightningproof", "Grants immunity to lightning attacks." } },
	{ 0x8029, { "Lightning Eater", "Converts lightning damage to HP." } },
	{ 0x802A, { "Waterstrike", "Adds water element to attacks and skills." } },
	{ 0x802B, { "Water Ward", "Reduces water damage by half." } },
	{ 0x802C, { "Waterproof", "Grants immunity to water attacks." } },
	{ 0x802D, { "Water Eater", "Converts water damage to HP." } },
	{ 0x802E, { "Deathstrike", "Almost always adds death to attacks and skills." } },
	{ 0x802F, { "Deathtouch", "Sometimes adds death to attacks and skills." } },
	{ 0x8030, { "Deathproof", "Almost completely protects against death." } },
	{ 0x8031, { "Death Ward", "Sometimes protects against death." } },
	{ 0x8032, { "Zombiestrike", "Almost always adds zombie to attacks and skills." } },
	{ 0x8033, { "Zombietouch", "Sometimes adds zombie to attacks and skills." } },
	{ 0x8034, { "Zombieproof", "Almost completely protects against zombie." } },
	{ 0x8035, { "Zombie Ward", "Sometimes protects against zombie." } },
	{ 0x8036, { "Stonestrike", "Almost always adds petrification to attacks and skills." } },
	{ 0x8037, { "Stonetouch", "Sometimes adds petrification to attacks and skills." } },
	{ 0x8038, { "Stoneproof", "Almost completely protects against petrification." } },
	{ 0x8039, { "Stone Ward", "Sometimes protects against petrification." } },
	{ 0x803A, { "Poisonstrike", "Almost always adds poison to attacks and skills." } },
	{ 0x803B, { "Poisontouch", "Sometimes adds poison to attacks and skills." } },
	{ 0x803C, { "Poisonproof", "Almost completely protects against poison." } },
	{ 0x803D, { "Poison Ward", "Sometimes protects against poison." } },
	{ 0x803E, { "Sleepstrike", "Almost always adds sleep to attacks and skills." } },
	{ 0x803F, { "Sleeptouch", "Sometimes adds sleep to attacks and skills." } },
	{ 0x8040, { "Sleepproof", "Almost completely protects against sleep." } },
	{ 0x8041, { "Sleep Ward", "Sometimes protects against sleep." } },
	{ 0x8042, { "Silencestrike", "Almost always adds silence to attacks and skills." } },
	{ 0x8043, { "Silencetouch", "Sometimes adds silence to attacks and skills." } },
	{ 0x8044, { "Silenceproof", "Almost completely protects against silence." } },
	{ 0x8045, { "Silence Ward", "Sometimes protects against silence." } },
	{ 0x8046, { "Darkstrike", "Almost always adds darkness to attacks and skills." } },
	{ 0x8047, { "Darktouch", "Sometimes adds darkness to attacks and skills." } },
	{ 0x8048, { "Darkproof", "Almost completely protects against darkness." } },
	{ 0x8049, { "Dark Ward", "Sometimes protects against darkness." } },
	{ 0x804A, { "Slowstrike", "Almost always adds slow to attacks and skills." } },
	{ 0x804B, { "Slowtouch", "Sometimes adds slow to attacks and skills." } },
	{ 0x804C, { "Slowproof", "Almost completely protects against slow." } },
	{ 0x804D, { "Slow Ward", "Sometimes protects against slow." } },
	{ 0x804E, { "Confuseproof", "Almost completely protects against confusion." } },
	{ 0x804F, { "Confuse Ward", "Sometimes protects against confusion." } },
	{ 0x8050, { "Berserkproof", "Almost completely protects against berserk." } },
	{ 0x8051, { "Berserk Ward", "Sometimes protects against berserk." } },
	{ 0x8052, { "Curseproof", "Almost completely protects against curse." } },
	{ 0x8053, { "Curse Ward", "Sometimes protects against curse." } },
	{ 0x8054, { "Auto-Shell", "Automatically casts Shell on user." } },
	{ 0x8055, { "Auto-Protect", "Automatically casts Protect on user." } },
	{ 0x8056, { "Auto-Haste", "Automatically casts Haste on user." } },
	{ 0x8057, { "Auto-Regen", "Automatically casts Regen on user." } },
	{ 0x8058, { "Auto-Reflect", "Automatically casts Reflect on user." } },
	{ 0x8059, { "SOS Shell", "Casts Shell when HP is low." } },
	{ 0x805A, { "SOS Protect", "Casts Protect when HP is low." } },
	{ 0x805B, { "SOS Haste", "Casts Haste when HP is low." } },
	{ 0x805C, { "SOS Regen", "Casts Regen when HP is low." } },
	{ 0x805D, { "SOS Reflect", "Casts Reflect when HP is low." } },
	{ 0x805E, { "SOS NulTide", "Casts NulTide when HP is low." } },
	{ 0x805F, { "SOS NulFrost", "Casts NulFrost when HP is low." } },
	{ 0x8060, { "SOS NulShock", "Casts NulShock when HP is low." } },
	{ 0x8061, { "SOS NulBlaze", "Casts NulBlaze when HP is low." } },
	{ 0x8062, { "Strength +3%", "Enhances physical attack power by 3%." } },
	{ 0x8063, { "Strength +5%", "Enhances physical attack power by 5%." } },
	{ 0x8064, { "Strength +10%", "Enhances physical attack power by 10%." } },
	{ 0x8065, { "Strength +20%", "Enhances physical attack power by 20%." } },
	{ 0x8066, { "Magic +3%", "Enhances magic attack power by 3%." } },
	{ 0x8067, { "Magic +5%", "Enhances magic attack power by 5%." } },
	{ 0x8068, { "Magic +10%", "Enhances magic attack power by 10%." } },
	{ 0x8069, { "Magic +20%", "Enhances magic attack power by 20%." } },
	{ 0x806A, { "Defense +3%", "Reduces damage from physical attacks by 3%." } },
	{ 0x806B, { "Defense +5%", "Reduces damage from physical attacks by 5%." } },
	{ 0x806C, { "Defense +10%", "Reduces damage from physical attacks by 10%." } },
	{ 0x806D, { "Defense +20%", "Reduces damage from physical attacks by 20%." } },
	{ 0x806E, { "Magic Def +3%", "Reduces damage from magical attacks by 3%." } },
	{ 0x806F, { "Magic Def +5%", "Reduces damage from magical attacks by 5%." } },
	{ 0x8070, { "Magic Def +10%", "Reduces damage from magical attacks by 10%." } },
	{ 0x8071, { "Magic Def +20%", "Reduces damage from magical attacks by 20%." } },
	{ 0x8072, { "HP +5%", "Raises max HP by 5%." } },
	{ 0x8073, { "HP +10%", "Raises max HP by 10%." } },
	{ 0x8074, { "HP +20%", "Raises max HP by 20%." } },
	{ 0x8075, { "HP +30%", "Raises max HP by 30%." } },
	{ 0x8076, { "MP +5%", "Raises max MP by 5%." } },
	{ 0x8077, { "MP +10%", "Raises max MP by 10%." } },
	{ 0x8078, { "MP +20%", "Raises max MP by 20%." } },
	{ 0x8079, { "MP +30%", "Raises max MP by 30%." } },
	{ 0x807A, { "Capture", "-" } },
	{ 0x807B, { "__", "Complete protection against instant death and all negative status effects except for Curse and Eject." } },
	{ 0x807C, { "Distill Power", "Adds Power Distiller effect to attacks and skills." } },
	{ 0x807D, { "Distill Mana", "Adds Mana Distiller effect to attacks and skills." } },
	{ 0x807E, { "Distill Speed", "Adds Speed Distiller effect to attacks and skills." } },
	{ 0x807F, { "Distill Ability", "Adds Ability Distiller effect to attacks and skills." } },
	{ 0x8080, { "Ribbon", "Almost completely protects against all status ailments." } },
	{ 0x8081, { "Extra 1", "-" } },
	{ 0x8082, { "Extra 2", "-" } },
	{ 0x8083, { "Extra 3", "-" } },
	{ 0x8084, { "Extra 4", "-" } },
	{ 0x8085, { "Extra 5", "-" } }

};