#include "_Item.h"
/*
	Key : Byte Value
	Value : Item Object { std::string name, std::string name }
*/
std::map<uint16_t, ItemObject> _Item = {
    { 0x00FF, { "None", "-" } },
    { 0x2000, { "Potion", "Restores 200 HP of one character." } },
    { 0x2001, { "Hi-Potion", "Restores 1000 HP of one character." } },
    { 0x2002, { "X-Potion", "Fully restores HP of one character." } },
    { 0x2003, { "Mega-Potion", "Restores 2000 HP of each party member." } },
    { 0x2004, { "Ether", "Restores 100 MP of one character." } },
    { 0x2005, { "Turbo Ether", "Restores 500 MP of one character." } },
    { 0x2006, { "Phoenix Down", "Revives one character from KO." } },
    { 0x2007, { "Mega Phoenix", "Revives party from KO." } },
    { 0x2008, { "Elixir", "Fully restores one character's HP & MP." } },
    { 0x2009, { "Megalixir", "Fully restores HP & MP of party." } },
    { 0x200A, { "Antidote", "Cures poison." } },
    { 0x200B, { "Soft", "Cures petrification." } },
    { 0x200C, { "Eye Drops", "Cures darkness." } },
    { 0x200D, { "Echo Screen", "Cures silence." } },
    { 0x200E, { "Holy Water", "Cures zombie and curse." } },
    { 0x200F, { "Remedy", "Cures all status abnormalities." } },
    { 0x2010, { "Power Distiller", "Makes one enemy drop Power Spheres." } },
    { 0x2011, { "Mana Distiller", "Makes one enemy drop Mana Spheres." } },
    { 0x2012, { "Speed Distiller", "Makes one enemy drop Speed Spheres." } },
    { 0x2013, { "Ability Distiller", "Makes one enemy drop Ability Spheres." } },
    { 0x2014, { "Al Bhed Potion", "Cures poison, silence, petrification. Gives 1000 HP to all." } },
    { 0x2015, { "Healing Water", "Fully restores HP of party." } },
    { 0x2016, { "Tetra Elemental", "Fully restores HP and casts NulAll on party." } },
    { 0x2017, { "Antarctic Wind", "Deals ice damage to an enemy." } },
    { 0x2018, { "Arctic Wind", "Deals ice damage to an enemy." } },
    { 0x2019, { "Ice Gem", "Deals ice damage to all enemies." } },
    { 0x201A, { "Bomb Fragment", "Deals fire damage to an enemy." } },
    { 0x201B, { "Bomb Core", "Deals fire damage to an enemy." } },
    { 0x201C, { "Fire Gem", "Deals fire damage to all enemies." } },
    { 0x201D, { "Electro Marble", "Deals lightning damage to an enemy." } },
    { 0x201E, { "Lightning Marble", "Deals lightning damage to an enemy." } },
    { 0x201F, { "Lightning Gem", "Deals lightning damage to all enemies." } },
    { 0x2020, { "Fish Scale", "Deals water damage to an enemy." } },
    { 0x2021, { "Dragon Scale", "Deals water damage to an enemy." } },
    { 0x2022, { "Water Gem", "Deals water damage to all enemies." } },
    { 0x2023, { "Grenade", "Damages all enemies." } },
    { 0x2024, { "Frag Grenade", "Inflicts damage and nullifies armored on all enemies." } },
    { 0x2025, { "Sleeping Powder", "Inflicts damage and sleep on all enemies." } },
    { 0x2026, { "Dream Powder", "Inflicts damage and sleep on all enemies." } },
    { 0x2027, { "Silence Grenade", "Inflicts damage and silence on all enemies." } },
    { 0x2028, { "Smoke Bomb", "Inflicts damage and darkness on all enemies." } },
    { 0x2029, { "Shadow Gem", "Reduces HP of all enemies by half." } },
    { 0x202A, { "Shining Gem", "Damages an enemy." } },
    { 0x202B, { "Blessed Gem", "Damages an enemy." } },
    { 0x202C, { "Supreme Gem", "Damages all enemies." } },
    { 0x202D, { "Poison Fang", "Inflicts damage and poison on an enemy." } },
    { 0x202E, { "Silver Hourglass", "Delays next turn of all enemies." } },
    { 0x202F, { "Gold Hourglass", "Damages all enemies and delays their next turn." } },
    { 0x2030, { "Candle of Life", "Casts Doom on an enemy." } },
    { 0x2031, { "Petrify Grenade", "Petrifies all enemies." } },
    { 0x2032, { "Farplane Shadow", "Inflicts death on an enemy." } },
    { 0x2033, { "Farplane Wind", "Inflicts death on all enemies." } },
    { 0x2034, { "Designer Wallet", "There seems to be some use for this..." } },
    { 0x2035, { "Dark Matter", "Deals major damage to all enemies." } },
    { 0x2036, { "Chocobo Feather", "Casts Haste on one character." } },
    { 0x2037, { "Chocobo Wing", "Casts Haste on party." } },
    { 0x2038, { "Lunar Curtain", "Casts Shell on one character." } },
    { 0x2039, { "Light Curtain", "Casts Protect on one character." } },
    { 0x203A, { "Star Curtain", "Casts Reflect on one character." } },
    { 0x203B, { "Healing Spring", "Casts Regen on one character." } },
    { 0x203C, { "Mana Spring", "Absorbs MP from an enemy." } },
    { 0x203D, { "Stamina Spring", "Absorbs HP from an enemy." } },
    { 0x203E, { "Soul Spring", "Absorbs HP & MP from an enemy." } },
    { 0x203F, { "Purifying Salt", "Damages an enemy and dispels its magic effects." } },
    { 0x2040, { "Stamina Tablet", "Doubles max HP of one character." } },
    { 0x2041, { "Mana Tablet", "Doubles max MP of one character." } },
    { 0x2042, { "Twin Stars", "Reduces MP cost of one character to 0." } },
    { 0x2043, { "Stamina Tonic", "Doubles max HP of party." } },
    { 0x2044, { "Mana Tonic", "Doubles max MP of party." } },
    { 0x2045, { "Three Stars", "Reduces party's MP cost to 0." } },
    { 0x2046, { "Power Sphere", "Activates nodes on Sphere Grid." } },
    { 0x2047, { "Mana Sphere", "Activates nodes on Sphere Grid." } },
    { 0x2048, { "Speed Sphere", "Activates nodes on Sphere Grid." } },
    { 0x2049, { "Ability Sphere", "Activates nodes on Sphere Grid." } },
    { 0x204A, { "Fortune Sphere", "Activates nodes on Sphere Grid." } },
    { 0x204B, { "Attribute Sphere", "Activates nodes used by allies on Sphere Grid." } },
    { 0x204C, { "Special Sphere", "Activates nodes used by allies on Sphere Grid." } },
    { 0x204D, { "Skill Sphere", "Activates nodes used by allies on Sphere Grid." } },
    { 0x204E, { "Wht Magic Sphere", "Activates nodes used by allies on Sphere Grid." } },
    { 0x204F, { "Blk Magic Sphere", "Activates nodes used by allies on Sphere Grid." } },
    { 0x2050, { "Master Sphere", "Activates any node on Sphere Grid." } },
    { 0x2051, { "Lv. 1 Key Sphere", "Opens Locks on Sphere Grid." } },
    { 0x2052, { "Lv. 2 Key Sphere", "Opens Locks on Sphere Grid." } },
    { 0x2053, { "Lv. 3 Key Sphere", "Opens Locks on Sphere Grid." } },
    { 0x2054, { "Lv. 4 Key Sphere", "Opens Locks on Sphere Grid." } },
    { 0x2055, { "HP Sphere", "Fills empty nodes on Sphere Grid." } },
    { 0x2056, { "MP Sphere", "Fills empty nodes on Sphere Grid." } },
    { 0x2057, { "Strength Sphere", "Fills empty nodes on Sphere Grid." } },
    { 0x2058, { "Defense Sphere", "Fills empty nodes on Sphere Grid." } },
    { 0x2059, { "Magic Sphere", "Fills empty nodes on Sphere Grid." } },
    { 0x205A, { "Magic Def Sphere", "Fills empty nodes on Sphere Grid." } },
    { 0x205B, { "Agility Sphere", "Fills empty nodes on Sphere Grid." } },
    { 0x205C, { "Evasion Sphere", "Fills empty nodes on Sphere Grid." } },
    { 0x205D, { "Accuracy Sphere", "Fills empty nodes on Sphere Grid." } },
    { 0x205E, { "Luck Sphere", "Fills empty nodes on Sphere Grid." } },
    { 0x205F, { "Clear Sphere", "Clears nodes from Sphere Grid." } },
    { 0x2060, { "Return Sphere", "Changes current location on Sphere Grid." } },
    { 0x2061, { "Friend Sphere", "Changes current location on Sphere Grid." } },
    { 0x2062, { "Teleport Sphere", "Changes current location on Sphere Grid." } },
    { 0x2063, { "Warp Sphere", "Changes current location on Sphere Grid." } },
    { 0x2064, { "Map", "Displays world map." } },
    { 0x2065, { "Rename Card", "Renames aeon." } },
    { 0x2066, { "Musk", "There seems to be some use for this..." } },
    { 0x2067, { "Hypello Potion", "There seems to be some use for this..." } },
    { 0x2068, { "Shining Thorn", "There seems to be some use for this..." } },
    { 0x2069, { "Pendulum", "There seems to be some use for this..." } },
    { 0x206A, { "Amulet", "There seems to be some use for this..." } },
    { 0x206B, { "Door to Tomorrow", "There seems to be some use for this..." } },
    { 0x206C, { "Wings to Discovery", "There seems to be some use for this..." } },
    { 0x206D, { "Gambler's Spirit", "There seems to be some use for this..." } },
    { 0x206E, { "Underdog's Secret", "There seems to be some use for this..." } },
    { 0x206F, { "Winning Formula", "There seems to be some use for this..." } }
};