#include "_KeyItem.h"
/*
Key : Bit Index
Value : Key Item Object { std::string name, std::string description  }
*/
std::map<uint16_t, KeyItemObject> _KeyItem = {
	{ 0, { "Withered Bouquet", "Someone put heart and soul into making this." } },
	{ 1, { "Flint", "Used to start fires." } },
	{ 2, { "Cloudy Mirror", "The surface is dark and clouded." } },
	{ 3, { "Celestial Mirror", "The surface is shiny and bright." } },
	{ 4, { "Al Bhed Primer I", "Teaches the letter \"A\" in Al Bhed." } },
	{ 5, { "Al Bhed Primer II", "Teaches the letter \"B\" in Al Bhed." } },
	{ 6, { "Al Bhed Primer III", "Teaches the letter \"C\" in Al Bhed." } },
	{ 7, { "Al Bhed Primer IV", "Teaches the letter \"D\" in Al Bhed." } },
	{ 8, { "Al Bhed Primer V", "Teaches the letter \"E\" in Al Bhed." } },
	{ 9, { "Al Bhed Primer VI", "Teaches the letter \"F\" in Al Bhed." } },
	{ 10, { "Al Bhed Primer VII", "Teaches the letter \"G\" in Al Bhed." } },
	{ 11, { "Al Bhed Primer VIII", "Teaches the letter \"H\" in Al Bhed." } },
	{ 12, { "Al Bhed Primer IX", "Teaches the letter \"I\" in Al Bhed." } },
	{ 13, { "Al Bhed Primer X", "Teaches the letter \"J\" in Al Bhed." } },
	{ 14, { "Al Bhed Primer XI", "Teaches the letter \"K\" in Al Bhed." } },
	{ 15, { "Al Bhed Primer XII", "Teaches the letter \"L\" in Al Bhed." } },
	{ 16, { "Al Bhed Primer XIII", "Teaches the letter \"M\" in Al Bhed." } },
	{ 17, { "Al Bhed Primer XIV", "Teaches the letter \"N\" in Al Bhed." } },
	{ 18, { "Al Bhed Primer XV", "Teaches the letter \"O\" in Al Bhed." } },
	{ 19, { "Al Bhed Primer XVI", "Teaches the letter \"P\" in Al Bhed." } },
	{ 20, { "Al Bhed Primer XVII", "Teaches the letter \"Q\" in Al Bhed." } },
	{ 21, { "Al Bhed Primer XVIII", "Teaches the letter \"R\" in Al Bhed." } },
	{ 22, { "Al Bhed Primer XIX", "Teaches the letter \"S\" in Al Bhed." } },
	{ 23, { "Al Bhed Primer XX", "Teaches the letter \"T\" in Al Bhed." } },
	{ 24, { "Al Bhed Primer XXI", "Teaches the letter \"U\" in Al Bhed." } },
	{ 25, { "Al Bhed Primer XXII", "Teaches the letter \"V\" in Al Bhed." } },
	{ 26, { "Al Bhed Primer XXIII", "Teaches the letter \"W\" in Al Bhed." } },
	{ 27, { "Al Bhed Primer XXIV", "Teaches the letter \"X\" in Al Bhed." } },
	{ 28, { "Al Bhed Primer XXV", "Teaches the letter \"Y\" in Al Bhed." } },
	{ 29, { "Al Bhed Primer XXVI", "Teaches the letter \"Z\" in Al Bhed." } },
	{ 30, { "Summoner's Soul", "Allows the aeons to learn abilities." } },
	{ 31, { "Aeon's Soul", "Allows you to raise aeons' attributes." } },
	{ 32, { "Jecht's Sphere", "A sphere recorded by Jecht ten years ago." } },
	{ 33, { "Rusty Sword", "An old, rusty sword." } },
	{ 34, { "-", "-" } },
	{ 35, { "Sun Crest", "A Celestial Token, fashioned in the shape of the Sun." } },
	{ 36, { "Sun Sigil", "A Celestial Token, fashioned in the shape of the Sun." } },
	{ 37, { "Moon Crest", "A Celestial Token, fashioned in the shape of the Moon." } },
	{ 38, { "Moon Sigil", "A Celestial Token, fashioned in the shape of the Moon." } },
	{ 39, { "Mars Crest", "A Celestial Token, fashioned in the shape of Mars." } },
	{ 40, { "Mars Sigil", "A Celestial Token, fashioned in the shape of Mars." } },
	{ 41, { "Mark of Conquest", "Given to those who have surpassed mortal bounds." } },
	{ 42, { "Saturn Crest", "A Celestial Token, fashioned in the shape of Saturn." } },
	{ 43, { "Saturn Sigil", "A Celestial Token, fashioned in the shape of Saturn." } },
	{ 44, { "Jupiter Crest", "A Celestial Token, fashioned in the shape of Jupiter." } },
	{ 45, { "Jupiter Sigil", "A Celestial Token, fashioned in the shape of Jupiter." } },
	{ 46, { "Venus Crest", "A Celestial Token, fashioned in the shape of Venus." } },
	{ 47, { "Venus Sigil", "A Celestial Token, fashioned in the shape of Venus." } },
	{ 48, { "Mercury Crest", "A Celestial Token, fashioned in the shape of Mercury." } },
	{ 49, { "Mercury Sigil", "A Celestial Token, fashioned in the shape of Mercury." } },
	{ 50, { "Blossom Crown", "Seems to have some connection with a hidden aeon..." } },
	{ 51, { "Flower Scepter", "Seems to have some connection with a hidden aeon..." } }
};