#include "_Overdrive.h"
/*
Key : Bit Index
Value : Overdrive Object { OverdriveType type, std::string name, std::string description }
*/
std::map<uint16_t, OverdriveObject> _Overdrive = {
	{ 0, { OverdriveType::TIDUS, "Spiral Cut", "Damages an enemy." } },
	{ 1, { OverdriveType::TIDUS, "Slice & Dice", "Damages all enemies." } },
	{ 2, { OverdriveType::TIDUS, "Energy Rain", "Damages all enemies." } },
	{ 3, { OverdriveType::TIDUS, "Blitz Ace", "Damages an enemy." } },
	{ 4, { OverdriveType::AURON, "Shooting Star", "Damages an enemy." } },
	{ 5, { OverdriveType::AURON, "Dragon Fang", "Damages all enemies." } },
	{ 6, { OverdriveType::AURON, "Banishing Blade", "Damages an enemy." } },
	{ 7, { OverdriveType::AURON, "Tornado", "Damages all enemies." } },
	{ 8, { OverdriveType::KIMAHRI, "Jump", "Damages an enemy." } },
	{ 9, { OverdriveType::KIMAHRI, "Fire Breath", "Deals fire damage to all enemies." } },
	{ 10, { OverdriveType::KIMAHRI, "Seed Cannon", "Damages an enemy." } },
	{ 11, { OverdriveType::KIMAHRI, "Self-Destruct", "Sacrifice life to heavily damage an enemy." } },
	{ 12, { OverdriveType::KIMAHRI, "Thrust Kick", "Deals damage and ejects enemy from battle." } },
	{ 13, { OverdriveType::KIMAHRI, "Stone Breath", "Petrifies all enemies." } },
	{ 14, { OverdriveType::KIMAHRI, "Aqua Breath", "Deals water damage to all enemies." } },
	{ 15, { OverdriveType::KIMAHRI, "Doom", "Counts down to an enemy's doom." } },
	{ 16, { OverdriveType::KIMAHRI, "White Wind", "Restores party's HP." } },
	{ 17, { OverdriveType::KIMAHRI, "Bad Breath", "Inflicts status ailments on all enemies." } },
	{ 18, { OverdriveType::KIMAHRI, "Mighty Guard", "Cast defensive spells on party." } },
	{ 19, { OverdriveType::KIMAHRI, "Nova", "Damages all enemies." } },
	{ 20, { OverdriveType::WAKKA, "Element Reels", "Spins elemental damage slots." } },
	{ 21, { OverdriveType::WAKKA, "Attack Reels", "Spins multiple attack slots." } },
	{ 22, { OverdriveType::WAKKA, "Status Reels", "Spins status ailment slots." } },
	{ 23, { OverdriveType::WAKKA, "Aurochs Reels", "Spins Aurochs custom slots." } },
	{ 24, { OverdriveType::LULU, "Blizzard Fury", "Cast multiple ice spells." } },
	{ 25, { OverdriveType::LULU, "Fire Fury", "Cast multiple fire spells." } },
	{ 26, { OverdriveType::LULU, "Thunder Fury", "Cast multiple lightning spells." } },
	{ 27, { OverdriveType::LULU, "Water Fury", "Cast multiple water spells." } },
	{ 28, { OverdriveType::LULU, "Fira Fury", "Cast multiple fire spells." } },
	{ 29, { OverdriveType::LULU, "Blizzara Fury", "Cast multiple ice spells." } },
	{ 30, { OverdriveType::LULU, "Thundara Fury", "Cast multiple lightning spells." } },
	{ 31, { OverdriveType::LULU, "Watera Fury", "Cast multiple water spells." } },
	{ 32, { OverdriveType::LULU, "Firaga Fury", "Cast multiple fire spells." } },
	{ 33, { OverdriveType::LULU, "Blizzaga Fury", "Cast multiple ice spells." } },
	{ 34, { OverdriveType::LULU, "Thundaga Fury", "Cast multiple lightning spells." } },
	{ 35, { OverdriveType::LULU, "Waterga Fury", "Cast multiple water spells." } },
	{ 36, { OverdriveType::LULU, "Bio Fury", "Cast multiple poison spells." } },
	{ 37, { OverdriveType::LULU, "Demi Fury", "Cast multiple spells that each reduce HP by 1/8." } },
	{ 38, { OverdriveType::LULU, "Death Fury", "Cast multiple Death spells." } },
	{ 39, { OverdriveType::LULU, "Drain Fury", "Cast multiple spells that absorb HP." } },
	{ 40, { OverdriveType::LULU, "Osmose Fury", "Cast multiple spells that absorb MP." } },
	{ 41, { OverdriveType::LULU, "Flare Fury", "Cast multiple non-elemental damage spells." } },
	{ 42, { OverdriveType::LULU, "Ultima Fury", "Cast multiple non-elemental damage spells." } },
	{ 43, { OverdriveType::RIKKU, "Grenade", "Damages all enemies." } },
	{ 44, { OverdriveType::RIKKU, "Frag Grenade", "Damage and Armor Break to all enemies." } },
	{ 45, { OverdriveType::RIKKU, "Pineapple", "Damages all enemies." } },
	{ 46, { OverdriveType::RIKKU, "Potato Masher", "Damages all enemies." } },
	{ 47, { OverdriveType::RIKKU, "Cluster Bomb", "Damages all enemies." } },
	{ 48, { OverdriveType::RIKKU, "Tallboy", "Damages all enemies." } },
	{ 49, { OverdriveType::RIKKU, "Blaster Mine", "Damage and status ailments to all enemies." } },
	{ 50, { OverdriveType::RIKKU, "Hazardous Shell", "Damage and status ailments to all enemies." } },
	{ 51, { OverdriveType::RIKKU, "Calamity Bomb", "Damage and status ailments to all enemies." } },
	{ 52, { OverdriveType::RIKKU, "Chaos Grenade", "Damage and status ailments to all enemies." } },
	{ 53, { OverdriveType::RIKKU, "Heat Blaster", "Deals fire damage to all enemies." } },
	{ 54, { OverdriveType::RIKKU, "Firestorm", "Deals fire damage to all enemies." } },
	{ 55, { OverdriveType::RIKKU, "Burning Soul", "Deals fire damage to all enemies." } },
	{ 56, { OverdriveType::RIKKU, "Brimstone", "Fire damage and status ailments to all enemies." } },
	{ 57, { OverdriveType::RIKKU, "Abaddon Flame", "Fire damage and status ailments to all enemies." } },
	{ 58, { OverdriveType::RIKKU, "Snow Flurry", "Deals ice damage to all enemies." } },
	{ 59, { OverdriveType::RIKKU, "Icefall", "Deals ice damage to all enemies." } },
	{ 60, { OverdriveType::RIKKU, "Winter Storm", "Deals ice damage to all enemies." } },
	{ 61, { OverdriveType::RIKKU, "Black Ice", "Ice damage and status ailments to all enemies." } },
	{ 62, { OverdriveType::RIKKU, "Krysta", "Ice damage and status ailments to all enemies." } },
	{ 63, { OverdriveType::RIKKU, "Thunderbolt", "Deals lightning damage to all enemies." } },
	{ 64, { OverdriveType::RIKKU, "Rolling Thunder", "Deals lightning damage to all enemies." } },
	{ 65, { OverdriveType::RIKKU, "Lightning Bolt", "Deals lightning damage to all enemies." } },
	{ 66, { OverdriveType::RIKKU, "Electroshock", "Lightning damage and status ailments to all enemies." } },
	{ 67, { OverdriveType::RIKKU, "Thunderblast", "Lightning damage and status ailments to all enemies." } },
	{ 68, { OverdriveType::RIKKU, "Waterfall", "Deals water damage to all enemies." } },
	{ 69, { OverdriveType::RIKKU, "Flash Flood", "Deals water damage to all enemies." } },
	{ 70, { OverdriveType::RIKKU, "Tidal Wave", "Deals water damage to all enemies." } },
	{ 71, { OverdriveType::RIKKU, "Aqua Toxin", "Water damage and status ailments to all enemies." } },
	{ 72, { OverdriveType::RIKKU, "Dark Rain", "Water damage and status ailments to all enemies." } },
	{ 73, { OverdriveType::RIKKU, "Nega Burst", "Reduces HP of all enemies by 3/4." } },
	{ 74, { OverdriveType::RIKKU, "Black Hole", "Reduces HP of all enemies by 15/16." } },
	{ 75, { OverdriveType::RIKKU, "Sunburst", "Deals damage to all enemies." } },
	{ 76, { OverdriveType::RIKKU, "Ultra Potion", "Restores HP of party." } },
	{ 77, { OverdriveType::RIKKU, "Panacea", "Cures party of all status ailments." } },
	{ 78, { OverdriveType::RIKKU, "Ultra Cure", "Restores HP and cures all status ailments of party." } },
	{ 79, { OverdriveType::RIKKU, "Mega Phoenix", "Revives party from KO status." } },
	{ 80, { OverdriveType::RIKKU, "Final Phoenix", "Revives party from KO status and fully restores HP." } },
	{ 81, { OverdriveType::RIKKU, "Elixir", "Fully restores HP & MP of one character." } },
	{ 82, { OverdriveType::RIKKU, "Megalixir", "Fully restores HP & MP of party." } },
	{ 83, { OverdriveType::RIKKU, "Super Elixir", "Full HP & MP to party and cures all status ailments." } },
	{ 84, { OverdriveType::RIKKU, "Final Elixir", "Restores party to full health." } },
	{ 85, { OverdriveType::RIKKU, "NulAll", "Defends a character from all elements." } },
	{ 86, { OverdriveType::RIKKU, "Mega NulAll", "Defends party from all elements." } },
	{ 87, { OverdriveType::RIKKU, "Hyper NulAll", "Defends party from all elements. Adds Cheer & Focus." } },
	{ 88, { OverdriveType::RIKKU, "Ultra NulAll", "Defends party from all elements and raises attributes." } },
	{ 89, { OverdriveType::RIKKU, "Mighty Wall", "Casts Shell and Protect on party." } },
	{ 90, { OverdriveType::RIKKU, "Mighty G", "Casts Shell, Protect, and Haste on party." } },
	{ 91, { OverdriveType::RIKKU, "Super Mighty G", "Casts Mighty G and Regen on party." } },
	{ 92, { OverdriveType::RIKKU, "Hyper Mighty G", "Casts Mighty G, Regen, and Auto-Life on party." } },
	{ 93, { OverdriveType::RIKKU, "Vitality", "Doubles max HP of one character." } },
	{ 94, { OverdriveType::RIKKU, "Mega Vitality", "Doubles max HP of party." } },
	{ 95, { OverdriveType::RIKKU, "Hyper Vitality", "Doubles max HP and bestows Cheer on party." } },
	{ 96, { OverdriveType::RIKKU, "Mana", "Doubles max MP of one character." } },
	{ 97, { OverdriveType::RIKKU, "Mega Mana", "Doubles max MP of party." } },
	{ 98, { OverdriveType::RIKKU, "Hyper Mana", "Doubles max MP and bestows Focus on party." } },
	{ 99, { OverdriveType::RIKKU, "Freedom", "Reduces MP cost of one character's abilities to 0." } },
	{ 100, { OverdriveType::RIKKU, "Freedom X", "Reduces MP cost of party's abilities to 0." } },
	{ 101, { OverdriveType::RIKKU, "Quartet of 9", "Augments one character's attacks to 9999 damage." } },
	{ 102, { OverdriveType::RIKKU, "Trio of 9999", "Augments party's attacks to 9999 damage." } },
	{ 103, { OverdriveType::RIKKU, "Hero Drink", "Allows character's attacks to deal critical damage." } },
	{ 104, { OverdriveType::RIKKU, "Miracle Drink", "Allows party's attacks to deal critical damage." } },
	{ 105, { OverdriveType::RIKKU, "Hot Spurs", "Accelerates party's Overdrive gauges." } },
	{ 106, { OverdriveType::RIKKU, "Eccentrick", "Hyper-accelerates party's Overdrive gauges." } },
	/* 107 - 108 is part of Misc. Command*/
	{ 109, { OverdriveType::VALEFOR, "Energy Blast", "Deals non-elemental damage to all enemies." } },
	{ 110, { OverdriveType::VALEFOR, "Energy Ray", "Deals non-elemental damage to all enemies." } },
	{ 113, { OverdriveType::IFRIT, "Hellfire", "Deals fire damage to all enemies." } },
	{ 116, { OverdriveType::IXION, "Thor's Hammer", "Deals lightning damage to all enemies." } },

	{ 119, { OverdriveType::SHIVA, "Diamond Dust", "Deals ice damage to all enemies." } },

	{ 122, { OverdriveType::BAHAMUT, "Mega Flare", "Deals non-elemental damage to all enemies." } },

	{ 125, { OverdriveType::ANIMA, "Oblivion", "Deals non-elemental damage to all enemies." } },
	{ 138, { OverdriveType::MAGUS_SISTERS, "Delta Attack", "The Magus Sisters' combined attack." } },
};